jwtIssuer.userpools                                    = ${COGNITO_USER_POOL_ID_DEFAULT}
jwtIssuer.path                                         = https://cognito-idp.%s.amazonaws.com/
jwtIssuer.fusionauth.issueruri                         = https://fleetgroup.dev
jwtIssuer.fusionauth.jwkseturi                         = http://host.docker.internal:9011/.well-known/jwks.json

bugsnag.active                                         = false
bugsnag.apiKey                                         =
bugsnag.send_uncaught_exceptions                       = false

aws.ssoProfile                                         = avr-dev-admin
aws.avrios.stage                                       = dev-${DEV_LOCAL_ENV:common}

spring.datasource.url                                  = jdbc:postgresql://host.docker.internal:5432/avrios?prepareThreshold=3&currentSchema=blueprint
spring.datasource.username                             = blueprint
spring.datasource.password                             = blueprint

spring.flyway.password                                 = flyway
spring.flyway.placeholders.schema                      = blueprint

coreClient.baseUrl                              = http://localhost:8080/api
coreClient.basicAuth.password                   = ENC(qjWyz2ZLGXOXOhSlWIUzH5quE8A5AGd9Zre3ihOLiXWGBagyft2RMlI52aL3pSgt)

springdoc.swagger-ui.enabled                           = true
