aws.ssoProfile                                         = avr-dev-admin
aws.avrios.stage                                       = dev-${DEV_LOCAL_ENV:common}

spring.datasource.url                                  = jdbc:postgresql://host.docker.internal:5432/avrios?prepareThreshold=3&currentSchema=antai
spring.datasource.username                             = antai
spring.datasource.password                             = antai

spring.flyway.password                                 = flyway
spring.flyway.placeholders.schema                      = antai

coreClient.basicAuth.password           = ENC(BKXchr9SpcBnkH6oS2vhBnZmN3kcfQR+0zEviXtNmq2MqOlxgaasLLUtBS/DjRvQVlHOjs2+M+5JHcXtR7dcCGSDw3x3YtNgo9r2D5VmZLo=)
coreClient.baseUrl                      = http://host.docker.internal:8080/api

springdoc.swagger-ui.enabled                           = true
