jwtIssuer.userpools                                    = local_123
jwtIssuer.path                                         = http://host.docker.internal:8077/jwk/%s/

bugsnag.active                                         = false
bugsnag.apiKey                                         =
bugsnag.send_uncaught_exceptions                       = false

aws.roleArn                                            = arn:aws:iam::821747761766:role/AccountDeveloperRole
aws.avrios.stage                                       = dev-${DEV_LOCAL_ENV:common}
