aws.ssoProfile                                         =
aws.avrios.stage                                       = ${spring.profiles.active}

spring.datasource.url                                  = jdbc:postgresql://antai-rds.avrios.com:5432/avrios?prepareThreshold=3&useSSL=true&requireSSL=true
spring.datasource.username                             = antai
spring.datasource.password                             = ENC(qOAZRr7BFOXuPUed71V4N4ZX83eCVj2+j+H8EIzjNvCkIa/JAwOo7bYp5ozdxsScMSii38xvl7RvYi5ne1ewhNTSPQv0svXoGFXHmJkjEmg=)

spring.flyway.password                                 = ENC(uJil+ZNx4lTYPlNsz2jDzd6U0xhZYXWIh/oWOcuVOq0wLfb3MezcAXkPF9GSULCBWJNJR3zuLy0hmdT4lejihK0amseLGOSngGf+/WxZxyw=)
spring.flyway.placeholders.schema                      = antai

coreClient.basicAuth.password           = ENC(zRP65heJauOs8Vp2f/jdrhKdRhx/XuyUoZ2u8O2tM781Ei/iMbcIUZ9OtKavveUDiG41h7WuLaJ7R1aR9tQnjYX4o4J1qJuhPF0ijrg6I1A=)
coreClient.baseUrl                      = https://api.avrios.com/api

springdoc.swagger-ui.enabled                           = false
