jwtIssuer.userpools                                    = eu-central-1_hw2uYZYJp
jwtIssuer.path                                         = https://cognito-idp.%s.amazonaws.com/

bugsnag.active                                         = true
bugsnag.apiKey                                         = <CHANGE-ME>
bugsnag.send_uncaught_exceptions                       = true

aws.roleArn                                            =
aws.avrios.stage                                       = ${spring.profiles.active}

spring.datasource.url                                  = jdbc:postgresql://avr-prod-blueprint.cui8f2ooiwoz.eu-central-1.rds.amazonaws.com:5432/avrios?prepareThreshold=3&useSSL=true&requireSSL=true
spring.datasource.username                             = blueprint
spring.datasource.password                             = ENC(3otz4VHXwPS/LrLuTKWTzAGvX7I2GDtoZnUjTbMoMX5jg/0xW8rr5ck5ApsYuQgiXu//upa5i2FEG8YKk8QsJPot4vt4Ie1sOFGY7z3+wkA=)

spring.flyway.password                                 = ENC(C1HYhd8S2znrtVD0Qye0V27dEcNyJ1B8dIW/tqwQV/1Mw5eBpWSOsj/R7ayklf6GkR8vmYINUygVoKWvELZT7g+ZkNE73TJuEyweAsM330Q=)
spring.flyway.placeholders.schema                      = public
