jwtIssuer.userpools                                    = eu-central-1_hw2uYZYJp
jwtIssuer.path                                         = https://cognito-idp.%s.amazonaws.com/

bugsnag.active                                         = true
bugsnag.apiKey                                         = <CHANGE-ME>
bugsnag.send_uncaught_exceptions                       = true

aws.roleArn                                            =
aws.avrios.stage                                       = ${spring.profiles.active}

spring.datasource.url                                  = jdbc:postgresql://blueprint-rds.avrios.com:5432/avrios?prepareThreshold=3&useSSL=true&requireSSL=true
spring.datasource.username                             = blueprint
spring.datasource.password                             = ENC(yqcyzelFyAo+/gLuO9vTDvfLC/bsHmrPmD+QRRlecFmzoNHC082fFOd1sXxF09yGlnGXs2TwAQJXkLUFPC2c408Jf6B6lotlLs3KNeWnu7c=)

spring.flyway.password                                 = ENC(FcOVRw+Ip/nbOF3Yc8Wf62jdOWFN/E/NFi8croTza5e3MLoo0Kny0tGTSZfUtBgITeLjir/Zk4i6k+iwCaZ8ocoPYomCthpBPUIYg2Cw4O0=)
spring.flyway.placeholders.schema                      = public
