jwtIssuer.userpools                                    = eu-central-1_T1udfGvfs
jwtIssuer.path                                         = https://cognito-idp.%s.amazonaws.com/

bugsnag.active                                         = true
bugsnag.apiKey                                         = <CHANGE-ME>
bugsnag.send_uncaught_exceptions                       = true
