jwtIssuer.userpools                                    = eu-central-1_T1udfGvfs
jwtIssuer.path                                         = https://cognito-idp.%s.amazonaws.com/

bugsnag.active                                         = true
bugsnag.apiKey                                         = <CHANGE-ME>
bugsnag.send_uncaught_exceptions                       = true

aws.roleArn                                            =
aws.avrios.stage                                       = ${spring.profiles.active}

spring.datasource.url                                  = jdbc:postgresql://avr-staging-blueprint.c8jzddhs7mz2.eu-central-1.rds.amazonaws.com:5432/avrios?prepareThreshold=3&useSSL=true&requireSSL=true
spring.datasource.username                             = blueprint
spring.datasource.password                             = ENC(3RYG81l0FNTMuHR1qL5R0AeHAOYM5mRj9uUOm9d9vOkw8WqecnDESxrkO0vFZCOU7liLKz2g0oc+CRX1tT1F2VSTHumViAb5iJE2/Fst9b0=)

spring.flyway.password                                 = ENC(dQsKZg5xpzePZBRVV8cvpGJf7FwiCn+0vA2rCEniw+qGREOcaCzuY3GLe1GBz6VsLPZ7MAY9i2zo0DhA4T05be0thJrETbXrytlHmXTX+mY=)
spring.flyway.placeholders.schema                      = public
