aws.ssoProfile                                         =
aws.avrios.stage                                       = ${spring.profiles.active}

spring.datasource.url                                  = jdbc:postgresql://antai-rds.staging.avrios.com:5432/avrios?prepareThreshold=3&useSSL=true&requireSSL=true
spring.datasource.username                             = antai
spring.datasource.password                             = ENC(oO/x9F0v7F/0T0AA1KJK1Vc2C+V/1+gw6r5YnVBCGiM7OY2cVVgfJrgqhodqX05RBWJrkDmnz2j/jImJrJWnsLlxUZdOMC1WH0VBIRYwA4Y=)

spring.flyway.password                                 = ENC(+aPdv+JmU32rr4/XAqNz/vzPwCAnw1vufGAGCO52XPZz4xBtXI/EBS+FrsEPfS+FT7lYgTEEflzPRaLJmRPBrqfXNvVOv9hFz7meDS1Ycqg=)
spring.flyway.placeholders.schema                      = public

coreClient.basicAuth.password           = ENC(DErRPn2JdXB5qB5IESZVYfphGl6JLRztsP7SMcIyazUXnJXGOKIaYOA0R6gu2PlhoEQy6dKm98TUYTzvrwR8XooEeEKJ6Fb0KlOb7s6i5i4=)
coreClient.baseUrl                      = https://api.staging.avrios.com/api

springdoc.swagger-ui.enabled                           = false
