jwtIssuer.userpools                                    = eu-central-1_mKcVhpIcj
jwtIssuer.path                                         = https://cognito-idp.%s.amazonaws.com/

bugsnag.active                                         = true
bugsnag.apiKey                                         = <CHANGE-ME>
bugsnag.send_uncaught_exceptions                       = true

aws.roleArn                                            =
aws.avrios.stage                                       = ${spring.profiles.active}

spring.datasource.url                                  = jdbc:postgresql://avr-test-blueprint.cj59igbvk4mv.eu-central-1.rds.amazonaws.com:5432/avrios?prepareThreshold=3&useSSL=true&requireSSL=true
spring.datasource.username                             = blueprint
spring.datasource.password                             = ENC(qooBupYaWjtK9lKAplU9R3NfPEfpvn3hi9LHufZ/g1G14DceCH+SPLRmzQxGNVj0CkHRBj+QLLWUklbsUpT/3bLy+S99KsV3RAiB9XDPqqc=)

spring.flyway.password                                 = ENC(udowlJjy4KhPAxl0mWTtbrWXf6/bgIoxVvzzZaRUKsY6uebE9uadJdElzV5vxRYC0xO7BJG2EBu96hg/VLs9BbLxt4yzvc0GVyS8gb7+t20=)
spring.flyway.placeholders.schema                      = public
