aws.ssoProfile                                         =
aws.avrios.stage                                       = ${spring.profiles.active}

spring.datasource.url                                  = jdbc:postgresql://antai-rds.test.avrios.io:5432/avrios?prepareThreshold=3&useSSL=true&requireSSL=true
spring.datasource.username                             = antai
spring.datasource.password                             = ENC(i8rCq3g2AW1VeqMD4UVofrESVDnh9OnGEHtgO3shTkroPufGByXjMtdudTEMif9WhF+g4sAiKIu7NY7CPHi9MqsY5RLO/kQwj/uJePQhi3I=)

spring.flyway.password                                 = ENC(Lc48ELeRayWBinud4F0RzL1T9lZzVxO4vsaxu7w2TezJGlVNI8G1oEwgLnLzxydHdzst6jTau7hyuAnTuwZlV8ET+IZoLq775K01vVsJMQ8=)
spring.flyway.placeholders.schema                      = antai

springdoc.swagger-ui.enabled                           = false
