version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain avrios --domain-owner 821747761766 --query authorizationToken --output text`
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - RELEASE_VERSION=${RELEASE_VERSION_PREFIX}${CODEBUILD_BUILD_NUMBER}${RELEASE_VERSION_POSTFIX}
  build:
    commands:
      - mvn versions:set versions:update-child-modules -DnewVersion=${RELEASE_VERSION} -s .build/codeartifact.xml
      - mvn clean deploy -s .build/codeartifact.xml
      - printf "[{\"name\":\"${CONTAINER_NAME}\",\"imageUri\":\"${REPOSITORY_URI}:${RELEASE_VERSION}\"}]" > imagedefinitions.json

artifacts:
  files:
    - 'imagedefinitions.json'

cache:
  paths:
    - '/root/.m2/**/*'
