version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 16
      docker: 20

  pre_build:
    commands:
      - aws codeartifact login --tool npm --repository avrios-npm --domain avrios
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain avrios --query authorizationToken --output text`
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - MAJOR_VERSION=1
      - RELEASE_VERSION=${RELEASE_VERSION_PREFIX}${MAJOR_VERSION}.${CODEBUILD_BUILD_NUMBER}${RELEASE_VERSION_POSTFIX}
      - echo ${RELEASE_VERSION}

  build:
    commands:
      - mvn versions:set versions:update-child-modules -DnewVersion=${RELEASE_VERSION} -s .build/codeartifact.xml
      - mvn clean deploy -s .build/codeartifact.xml
      - printf "{\"imageTag\":\"${RELEASE_VERSION}\"}" > imagedefinitions.json

  post_build:
    commands:
      - rm -rf /root/.m2/repository/com/avrios/blueprint

artifacts:
  files:
    - 'imagedefinitions.json'
    - 'release/infrastructure/cdk.out/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
