version: 0.2

env:
  shell: bash

run-as: codebuild-user

phases:
  install:
    run-as: root
    runtime-versions:
      java: corretto21
      nodejs: 18
      avrios: 1
    commands:
      - restore-maven-cache -u codebuild-user

  pre_build:
    commands:
      - MAJOR_VERSION=1
      - RELEASE_VERSION=${RELEASE_VERSION_PREFIX}${MAJOR_VERSION}.${CODEBUILD_BUILD_NUMBER}${RELEASE_VERSION_POSTFIX}
      - echo ${RELEASE_VERSION}

  build:
    commands:
      - mvn versions:set versions:update-child-modules -DnewVersion=${RELEASE_VERSION} -s .build/codeartifact.xml
      - HOME=/home/codebuild-user mvn clean deploy -Ddocker.tags.latest=${DOCKER_TAGS_LATEST} -s .build/codeartifact.xml
      - printf "{\"imageTag\":\"${RELEASE_VERSION}\"}" > imagedefinitions.json

  post_build:
    commands:
      - prepare-maven-cache -u codebuild-user -p com/avrios/blueprint
      # Tag git on RELEASE-* versions
      - if [[ $RELEASE_VERSION_PREFIX == RELEASE* ]]; then publish-git-tag --tag ${RELEASE_VERSION} --source-commit ${CODEBUILD_RESOLVED_SOURCE_VERSION} --repository blueprint-service --gh-token ${GITHUB_TOKEN}; fi

artifacts:
  files:
    - 'imagedefinitions.json'
    - 'release/infrastructure/cdk.out/*'
  discard-paths: yes

cache:
  paths:
    - '/home/codebuild-user/maven_cache.tar'
