## Spring Boot
server.port                                            = @exec.config.port@
server.servlet.contextPath                             = /@avr.service.name.short@
# increase max http request header size (from default 8KB) to match the AWS API Gateway hard limit
server.max-http-request-header-size             = 10240B

management.endpoints.web.base-path                     = /
management.endpoints.web.path-mapping.health           = healthCheck
management.endpoints.web.exposure.include              = health, info
management.endpoint.health.show-details                = always
management.endpoint.health.show-components             = always

management.metrics.web.server.request.autotime.enabled = false
management.metrics.web.client.request.autotime.enabled = false

## User pool
jwtIssuer.userpools                                    = @jwtIssuer.userpools@
jwtIssuer.path                                         = @jwtIssuer.path@
jwtIssuer.fusionauth.issueruri                         = @jwtIssuer.fusionauth.issueruri@
jwtIssuer.fusionauth.jwkseturi                         = @jwtIssuer.fusionauth.jwkseturi@

## Bugsnag
bugsnag.active                                         = @bugsnag.active@
bugsnag.apiKey                                         = @bugsnag.apiKey@
bugsnag.send_uncaught_exceptions                       = @bugsnag.send_uncaught_exceptions@

## AWS
aws.ssoProfile                                         = @aws.ssoProfile@
aws.avrios.stage                                       = @aws.avrios.stage@
aws.queue.simpleJob                                    = ${aws.avrios.stage}-blueprint-jobSimple.fifo
aws.queue.complexJob                                   = ${aws.avrios.stage}-blueprint-jobComplex.fifo


## Persistence

### App datasource
spring.datasource.url                                  = @spring.datasource.url@
spring.datasource.username                             = @spring.datasource.username@
spring.datasource.password                             = @spring.datasource.password@

### Hibernate
spring.jpa.hibernate.ddl-auto                          = validate
spring.jpa.hibernate.naming.physical-strategy          = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.show_sql                                    = false
spring.jpa.properties.hibernate.format_sql             = false
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type = VARCHAR

### Flyway
spring.flyway.user                                     = flyway
spring.flyway.password                                 = @spring.flyway.password@
spring.flyway.url                                      = @spring.datasource.url@
spring.flyway.out-of-order                             = true
spring.flyway.table                                    = schema_version
spring.flyway.placeholders.schema                      = @spring.flyway.placeholders.schema@
spring.flyway.placeholders.app-user.user               = @spring.datasource.username@
spring.flyway.placeholders.app-user.password           = @spring.datasource.password@
spring.flyway.locations                                = classpath:db/migration

### Core
coreClient.baseUrl                                     = @coreClient.baseUrl@
coreClient.basicAuth.username                          = core
coreClient.basicAuth.password                          = @coreClient.basicAuth.password@

springdoc.swagger-ui.enabled                           = @springdoc.swagger-ui.enabled@
