###
### Spring Boot
###
server.port                                      = @exec.config.port@
server.servlet.contextPath                       = /blueprint

management.endpoints.web.base-path               = /
management.endpoints.web.path-mapping.health     = healthCheck
management.endpoints.web.exposure.include        = health
management.endpoint.health.show-details          = always
management.endpoint.health.show-components       = always

management.metrics.web.server.auto-time-requests = false
