###
### Spring Boot
###
server.port                                            = @exec.config.port@
server.servlet.contextPath                             = /@avr.service.name.short@

management.endpoints.web.base-path                     = /
management.endpoints.web.path-mapping.health           = healthCheck
management.endpoints.web.exposure.include              = health, info
management.endpoint.health.show-details                = always
management.endpoint.health.show-components             = always

management.metrics.web.server.request.autotime.enabled = false

## User pool
jwtIssuer.userpools                                    = @jwtIssuer.userpools@
jwtIssuer.path                                         = @jwtIssuer.path@

## Bugsnag
bugsnag.active                                         = @bugsnag.active@
bugsnag.apiKey                                         = @bugsnag.apiKey@
bugsnag.send_uncaught_exceptions                       = @bugsnag.send_uncaught_exceptions@
