CREATE SCHEMA IF NOT EXISTS ${schema};
CREATE USER antai WITH PASSWORD '${app-user.password}' login;
GRANT USAGE ON SCHEMA ${schema} TO antai;
GRANT ALL ON TABLE schema_version TO antai;
ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema} GRANT SELECT, INSERT, DELETE, UPDATE ON TABLES TO antai;
ALTER DEFAULT PRIVILEGES IN SCHEMA ${schema} GRANT ALL ON SEQUENCES TO antai;
